version: "3.9"

services:
  bookings-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: bookings
      POSTGRES_PASSWORD: bookings
      POSTGRES_DB: bookings
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "54321:5432"
    volumes:
      - "./.docker/db/data:/var/lib/postgresql/data:rw"

